In [ ]:
Introduccion -> Que datos, de donde son, que idea hay
Motivacion -> Que esperamos conseguir
Aplicacion -> codigo
Resultados -> que conseguimos
Conclusiones -> Comentar lo que se consigue

In [1]:
import pandas as pd

In [5]:
ruta = './bomberos/ActuacionesBomberos_'
fechas = ['2017', '2018', '2019', '2020', '2021', '2022', '2023']
dataframes = []

encoding='ISO-8859-1'

for fecha in fechas:
    df = pd.read_csv(ruta+fecha+'.csv', sep=';', skiprows=0, encoding=encoding)

    dataframes.append(df)
    if fecha == '2019':
        encoding='utf-8'


    
resultado = pd.concat(dataframes, ignore_index=True)
resultado.dropna(inplace=True)
resultado

,AÑO,MES,DISTRITO,FUEGOS,DAÑOS EN CONSTRUCCION,SALVAMENTOS Y RESCATES,DAÑOS POR AGUA,INCIDENTES DIVERSOS,SALIDAS SIN INTERVENCION,SERVICIOS VARIOS,TOTAL
0,2017,Agosto,CENTRO,47.0,20.0,44.0,26.0,34.0,19.0,9.0,199.0
1,2017,Agosto,ARGANZUELA,24.0,5.0,20.0,15.0,28.0,13.0,3.0,108.0
2,2017,Agosto,RETIRO,11.0,7.0,12.0,9.0,30.0,3.0,1.0,73.0
3,2017,Agosto,SALAMANCA,19.0,12.0,20.0,17.0,32.0,4.0,1.0,105.0
4,2017,Agosto,CHAMARTIN,15.0,6.0,21.0,8.0,34.0,11.0,2.0,97.0
...,...,...,...,...,...,...,...,...,...,...,...
1619,2023,enero,VILLA DE VALLECAS,15.0,7.0,19.0,5.0,7.0,22.0,2.0,77.0
1620,2023,enero,VICALVARO,9.0,5.0,8.0,3.0,8.0,6.0,2.0,41.0
1621,2023,enero,SAN BLAS,16.0,3.0,25.0,4.0,10.0,20.0,1.0,79.0
1622,2023,enero,BARAJAS,1.0,2.0,4.0,2.0,15.0,13.0,8.0,45.0
1623,2023,enero,FUERA DEL TÉRMINO MUNICIPAL,0.0,0.0,0.0,0.0,2.0,1.0,0.0,3.0

In [6]:
ruta = './samur/activaciones_samur_'
fechas = ['2017', '2018', '2019', '2020', '2021', '2022', '2023']
dataframes = []

encoding='ISO-8859-1'

for fecha in fechas:
    df = pd.read_csv(ruta+fecha+'.csv', sep=';', skiprows=0, encoding=encoding)

    dataframes.append(df)
    if fecha == '2019':
        encoding='utf-8'


    
samur = pd.concat(dataframes, ignore_index=True)
samur.drop(columns=['Hora Solicitud', 'Hora Intervención', 'Hospital'], inplace=True)

In [7]:
samur

         Año         Mes                         Código           Distrito
0       2017       ENERO                        Heridas             CENTRO
1       2017       ENERO       Agresión sin especificar        CARABANCHEL
2       2017       ENERO           Intoxicación etílica          SALAMANCA
3       2017       ENERO       Agresión sin especificar             CENTRO
4       2017       ENERO  Accidente menos de 3 victimas  VILLA DE VALLECAS
...      ...         ...                            ...                ...
930214  2023  SEPTIEMBRE             Casual: caída, etc           SAN BLAS
930215  2023  SEPTIEMBRE       Convulsión y/o epilepsia           CHAMBERI
930216  2023  SEPTIEMBRE           Intoxicación etílica           CHAMBERI
930217  2023  SEPTIEMBRE           Intoxicación etílica             TETUAN
930218  2023  SEPTIEMBRE       Patología cardiovascular      CIUDAD LINEAL

[930219 rows x 4 columns]

In [70]:
import requests
import pandas as pd

for numero in range(0, 119):
    url = 'https://datos.madrid.es/egob/catalogo/212616-'+ str(numero) +'-policia-estadisticas.xlsx'
    extension = '.xlsx'
    respuesta = requests.get(url)
    
    if respuesta.status_code == 404:
        url = 'https://datos.madrid.es/egob/catalogo/212616-'+ str(numero) +'-policia-estadisticas.xls'
        respuesta = requests.get(url)
        extension = '.xls'
    


    if respuesta.status_code == 200:

        with open('./policia/policia'+str(numero)+extension, 'wb') as archivo_local:
            archivo_local.write(respuesta.content)